---
- name: Install Clickhouse
  hosts: clickhouse
  become: true
  handlers:
    - name: Start clickhouse service
      ansible.builtin.service:
        name: clickhouse-server
        state: started
      tags:
        - clickhouse
        - start

    - name: Get clickhouse packages
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_amd64.deb"
        dest: "/tmp/clickhouse/{{ item }}_{{ clickhouse_version }}_amd64.deb"
        mode: "0644"
      loop: "{{ clickhouse_packages }}"
      tags:
        - clickhouse
        - packages

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install clickhouse packages
      ansible.builtin.apt:
        deb: "/tmp/clickhouse/{{ item }}_{{ clickhouse_version }}_amd64.deb"
      loop: "{{ clickhouse_packages }}"
      notify: Start clickhouse service
      changed_when: false
      tags:
        - clickhouse
        - packages
        - install

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
      tags:
        - clickhouse
        - service start

    - name: Wait for clickhouse-server to be ready
      ansible.builtin.wait_for:
        host: localhost
        port: "9000"
        delay: "10"
        timeout: "300"
      tags:
        - clickhouse
        - wait

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
      tags:
        - clickhouse
        - create db

- name: Install Vector
  hosts: vector
  become: true
  handlers:
    - name: Start vector service
      ansible.builtin.service:
        name: vector
        state: restarted
      tags:
        - vector
        - restart

  tasks:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
        dest: "/tmp/vector-{{ vector_version }}.deb"
        mode: "0644"
      tags:
        - vector
        - packages

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install vector packages
      ansible.builtin.command:
        cmd: "dpkg -i /tmp/vector-{{ vector_version }}.deb"
      changed_when: false
      tags:
        - vector
        - packages
        - install

    - name: Deploy vector configuration
      ansible.builtin.template:
        src: templates/vector.j2
        dest: "{{ vector_config_path }}"
        mode: "0644"
      notify: Start vector service
      tags:
        - vector
        - packages
        - install

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
      tags:
        - vector
        - restart service
