---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.135.184
      ansible_user: ansible
      ansible_ssh_private_key_file: "/home/myash/.ssh/id_rsa"
vector:
  hosts:
    vector:
      ansible_host: 158.160.152.195
      ansible_user: ansible
      ansible_ssh_private_key_file: "/home/myash/.ssh/id_rsa"
